namespace {NAMESPACE};
<!-- BEGIN USED_CLASSES -->
use {USE_CLASS}{AS_CLASS};
<!-- END USED_CLASSES -->

{ABSTRACT}class {NAME}{EXTENDS}{IMPLEMENTS} {
<!-- BEGIN PROPERTIES -->
{PROPERTY}
<!-- END PROPERTIES -->
<!-- BEGIN METHODS -->
{METHOD}
<!-- END METHODS -->
}