namespace {NAMESPACE};
<!-- BEGIN USED_CLASSES -->
use {USE_CLASS}{AS_CLASS};
<!-- END USED_CLASSES -->{USED_CLASSES_EOL}
{ABSTRACT}class {NAME}{EXTENDS}{IMPLEMENTS} {
<!-- BEGIN PROPERTIES -->
{PROPERTY}
<!-- END PROPERTIES -->{PROPERTIES_EOL}<!-- BEGIN METHODS -->
{METHOD}
<!-- END METHODS -->
}