	/**<!-- BEGIN DESCRIPTION_BLOCK -->
	 * {DESCRIPTION}
	<!-- END DESCRIPTION_BLOCK -->
	 *<!-- BEGIN PARAMETERS_BLOCK -->
	 * @param {PARAM_TYPE} {PARAM_NAME}
	 <!-- END PARAMETERS_BLOCK -->
	 */
	{VISIBILITY}{STATIC} function {NAME}({PARAMETERS}) {
{BODY}
	}
